version: '3.8'

services:
  web:
    build: .
    container_name: djangoapp
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./vite-project/
      dockerfile: Dockerfile
    container_name: vite_react_app
    ports:
      - "5173:5173" 
  
