version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"  


  frontend:
    build:
      context: ./vite-project/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"  

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8080:8080"  # HTTP on port 8080
  #     - "8443:8443"  # HTTPS on port 8443
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./ssl:/etc/nginx/ssl  # SSL certificates directory
  #     - ./certbot/www:/var/www/certbot  # Certbot challenge directory
  #   depends_on:
  #     - backend

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt  # Certbot config and certificates
  #     - ./certbot/www:/var/www/certbot  # Webroot directory for challenge
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $!; certbot renew; done;'"