version: '3.8'

services:
  # db:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: connection
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: ta35mysql
  #     MYSQL_ROOT_PASSWORD: your_root_password
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

  web:
    image: django-app:latest
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_NAME=your_db_name
    #   - DB_USER=your_db_user
    #   - DB_PASSWORD=your_db_password

# volumes:
#   mysql_data: