version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"  


  frontend:
    build:
      context: ./vite-project/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"  

