# Generated by Django 4.2.8 on 2024-08-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sim", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tree",
            new_name="Name",
        ),
    ]
